services:
  db:
    image: postgres:latest
    container_name: adlibai_postgres
    restart: always
    environment:
      POSTGRES_USER: adlibai
      POSTGRES_PASSWORD: adlibai
      POSTGRES_DB: adlibai
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
